#!/bin/sh
#. /etc/os-release
PRETTY_NAME=`awk -F= '$1=="PRETTY_NAME" { print $2 ;}' /etc/os-release | tr -d '"'`
VERSION_ID=`awk -F= '$1=="VERSION_ID" { print $2 ;}' /etc/os-release`
UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINUTES=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)
cat > /etc/motd << EOF

  Authorized access only!

  Hostname: `hostname`
  Kernel: `uname -r`
  Version $VERSION_ID
  Available Updates: `apk update >/dev/null && apk -u list | wc -l`

  Uptime: $UPTIME_DAYS days, $UPTIME_HOURS hours, $UPTIME_MINUTES minutes
  CPU Load: `cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3}'`

  Memory: `free -m | head -n 2 | tail -n 1 | awk {'print  $2'}`M
  Free Memory: `free -m | head -n 2 | tail -n 1 | awk {'print $4'}`M

  Disk: `df -h / | awk  '{ a = $2 } END { print a }'`
  Free Disk: `df -h / | awk '{ a =  $4 } END { print a }'`

  eth0 Address: `ifconfig eth0 | grep "inet addr" |  awk -F: '{print $2}' | awk '{print $1}'`

EOF
